{{- range .Values.clusters }}
{{- if .apps.istio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-%s" .name "istio"}}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .project }}
  source: 
    repoURL: https://github.com/samng1991/hkjc-test.git
    targetRevision: {{ .apps.istio.version }} # commit, tag, branch
    path: applications/istio
    helm:
      releaseName: istio
      version: v3
  destination:
    server: {{ .destinationServer }}
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
---

{{- end }}
