{{- range .Values.clusters }}
{{- if .apps.certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-%s" .name "cert-manager"}}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .project }}
  source: 
    repoURL: https://charts.jetstack.io
    targetRevision: {{ .apps.certManager.version }} # commit, tag, branch
    chart: cert-manager
    helm:
      releaseName: cert-manager
      parameters:
      - name: "installCRDs"
        value: "true"
    #   - name: "global.rbac.create"
    #     value: "false"
    #   - name: "serviceAccount.create"
    #     value: "false"
    #   - name: "serviceAccount.name"
    #     value: cert-manager
    #   - name: "webhook.serviceAccount.create"
    #     value: "false"
    #   - name: "webhook.serviceAccount.name"
    #     value: cert-manager-webhook
    #   - name: "cainjector.serviceAccount.create"
    #     value: "false"
    #   - name: "cainjector.serviceAccount.name"
    #     value: cert-manager-cainjector  
      version: v3
  destination:
    server: {{ .destinationServer }}
    namespace: cert-manager
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group:  apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: certificaterequests.cert-manager.io
    jsonPointers:
      - /status
  - group:  apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: certificates.cert-manager.io
    jsonPointers:
      - /status
  - group:  apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: challenges.cert-manager.io
    jsonPointers:
      - /status
  - group:  apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: challenges.acme.cert-manager.io
    jsonPointers:
      - /status
  - group:  apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: clusterissuers.cert-manager.io
    jsonPointers:
      - /status
  - group:  apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: issuers.cert-manager.io
    jsonPointers:
      - /status
  - group:  apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: orders.acme.cert-manager.io
    jsonPointers:
      - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
---

{{- end }}
